# Generated by Django 3.2.8 on 2021-11-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='order_gross',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='lineitem_total',
            new_name='lineitem_gross',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
    ]
