# Generated by Django 3.2.8 on 2021-12-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('comment', models.TextField(max_length=1000)),
                ('style', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
